import {expect,test} from '@playwright/test'
for(const width of [1440,390])test(`bottom board-connect button selects a real port and requires confirmation at ${width}px`,async({page,request})=>{
 const project=await(await request.post('/api/hardware/projects',{data:{name:'Flash dialog',board:'arduino-uno'}})).json()
 await page.setViewportSize({width,height:900})
 await page.route('**/api/hardware/devices',route=>route.fulfill({json:{devices:[{port:'COM8',label:'COM8',boards:[{name:'Arduino Uno',fqbn:'arduino:avr:uno'}]}]}}))
 await page.goto(`/project/${project.id}`)
 await page.getByRole('button',{name:'Connect board & flash',exact:true}).click()
 const dialog=page.getByRole('dialog',{name:'Connect and flash board'})
 await expect(dialog).toBeVisible()
 await dialog.getByLabel('Connected board port').selectOption('COM8')
 await expect(dialog.getByRole('button',{name:'Flash code to board',exact:true})).toBeDisabled()
 await dialog.getByRole('checkbox').check()
 await expect(dialog).toContainText('Save and compile')
 await expect(dialog.getByRole('button',{name:'Flash code to board',exact:true})).toBeDisabled()
 await dialog.getByRole('button',{name:'Close board connection'}).click()
 await expect(dialog).toHaveCount(0)
})

test('current firmware requires explicit confirmation and renders uploader result',async({page,request})=>{
 test.setTimeout(150000)
 const project=await(await request.post('/api/hardware/projects',{data:{name:'Flash current source',board:'arduino-uno'}})).json()
 const compiled=await request.post(`/api/hardware/project/${project.id}/command`,{data:{name:'compile_firmware',args:{}},timeout:120000})
 expect(compiled.ok()).toBe(true)
 await page.route('**/api/hardware/devices',route=>route.fulfill({json:{devices:[{port:'COM8',label:'COM8',boards:[{name:'Arduino Uno'}]}]}}))
 let uploads=0
 await page.route(`**/api/hardware/projects/${project.id}/flash`,route=>{uploads++;const body=route.request().postDataJSON();expect(body.confirm).toBe(true);expect(body.port).toBe('COM8');expect(Object.keys(body)).toEqual(['port','expected_revision','source_revision','confirm']);return route.fulfill({json:{success:true,stdout:'Uploader verified firmware',stderr:''}})})
 await page.goto(`/project/${project.id}`)
 await page.getByRole('button',{name:'Connect board & flash',exact:true}).click()
 const dialog=page.getByRole('dialog',{name:'Connect and flash board'})
 await dialog.getByLabel('Connected board port').selectOption('COM8')
 const flash=dialog.getByRole('button',{name:'Flash code to board',exact:true})
 await expect(flash).toBeDisabled();expect(uploads).toBe(0)
 await dialog.getByRole('checkbox').check();await expect(flash).toBeEnabled();await flash.click()
 await expect(dialog).toContainText('Uploader reported success on COM8')
 expect(uploads).toBe(1)
})

test('no-board state is explicit and does not fake a connection',async({page,request})=>{
 const project=await(await request.post('/api/hardware/projects',{data:{name:'No device',board:'arduino-uno'}})).json()
 await page.route('**/api/hardware/devices',route=>route.fulfill({json:{devices:[]}}))
 await page.goto(`/project/${project.id}`)
 await page.getByRole('button',{name:'Connect board & flash',exact:true}).click()
 await expect(page.getByRole('dialog',{name:'Connect and flash board'})).toContainText('No serial boards detected')
})
