import {expect,test} from '@playwright/test'
for(const board of ['arduino-uno','arduino-nano','arduino-mega'])test(`${board} DIP channels drive actual independent pulled-up inputs`,async({page,request})=>{
 test.setTimeout(150000)
 const project=await(await request.post('/api/hardware/projects',{data:{name:'DIP controls',board}})).json()
 const command=async(name:string,args:Record<string,unknown>)=>{const r=await request.post(`/api/hardware/project/${project.id}/command`,{data:{name,args}});expect(r.ok(),await r.text()).toBe(true)}
 await command('add_component',{type:'dip-switch-8',id:'dip',x:420,y:150})
 for(const [pin,target] of [['6','1a'],['7','2a'],['GND','1b'],['GND','2b']])await command('connect_wire',{from:{component:'board',pin},to:{component:'dip',pin:target}})
 await command('generate_firmware',{source:'void setup(){Serial.begin(9600);pinMode(6,INPUT_PULLUP);pinMode(7,INPUT_PULLUP);}\nvoid loop(){Serial.print(digitalRead(6));Serial.print(",");Serial.println(digitalRead(7));delay(50);}'})
 await command('compile_firmware',{})
 await page.goto(`/project/${project.id}`)
 await expect(page.getByText('Runtime: Connected',{exact:true})).toBeVisible({timeout:30000})
 await page.getByRole('button',{name:'Run',exact:true}).click()
 await page.getByRole('button',{name:'Serial monitor',exact:true}).click()
 const output=page.getByLabel('Serial output',{exact:true})
 await expect(output).toContainText('1,1',{timeout:10000})
 await page.locator('wokwi-dip-switch-8').evaluate(element=>{(element as HTMLElement &{values:number[]}).values=[1,0,0,0,0,0,0,0];element.dispatchEvent(new Event('change'))})
 await expect(output).toContainText('0,1',{timeout:10000})
 await page.locator('wokwi-dip-switch-8').evaluate(element=>{(element as HTMLElement &{values:number[]}).values=[0,1,0,0,0,0,0,0];element.dispatchEvent(new Event('change'))})
 await expect(output).toContainText('1,0',{timeout:10000})
 await page.getByRole('button',{name:'Stop',exact:true}).click()
 await page.getByRole('button',{name:'Run',exact:true}).click()
 await expect(page.getByRole('button',{name:'Stop',exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Stop',exact:true}).click()
})
