import {expect,test} from '@playwright/test'
test('actual C3 firmware associates with the configured simulated access point',async({page,request})=>{
 test.setTimeout(720000)
 const project=await(await request.post('/api/hardware/projects',{data:{name:'Internal WiFi',board:'esp32-c3'}})).json()
 const edited=await request.post(`/api/hardware/project/${project.id}/command`,{data:{name:'generate_firmware',args:{source:'#include <WiFi.h>\nvoid setup(){Serial.begin(115200);WiFi.mode(WIFI_STA);WiFi.begin("WireUpTest","wireuptest123");unsigned long start=millis();while(WiFi.status()!=WL_CONNECTED && millis()-start<20000)delay(100);Serial.println(WiFi.status()==WL_CONNECTED?"SIM_WIFI_CONNECTED":"SIM_WIFI_FAILED");}\nvoid loop(){delay(1000);}'}}})
 expect(edited.ok()).toBe(true)
 const result=await request.post(`/api/hardware/project/${project.id}/command`,{data:{name:'compile_firmware',args:{}},timeout:650000});expect(result.ok(),await result.text()).toBe(true)
 await page.goto(`/project/${project.id}`)
 await page.getByRole('button',{name:'Select board',exact:true}).click()
 await page.getByRole('button',{name:'Simulated Wi-Fi settings'}).click()
 const dialog=page.getByRole('dialog',{name:'Simulated Wi-Fi network'})
 await dialog.getByLabel('Simulated network SSID').fill('WireUpTest');await dialog.getByLabel('Simulated network password').fill('wireuptest123')
 await dialog.getByRole('button',{name:'Apply network settings'}).click();await dialog.getByRole('button',{name:'Close simulated Wi-Fi'}).click()
 await page.getByRole('button',{name:'Run',exact:true}).click()
 await expect(page.getByRole('button',{name:'Stop',exact:true})).toBeVisible({timeout:60000})
 await page.getByRole('button',{name:'Serial monitor',exact:true}).click()
 await expect(page.getByLabel('Serial output',{exact:true})).toContainText('SIM_WIFI_CONNECTED',{timeout:60000})
 await page.getByRole('button',{name:'Stop',exact:true}).click()
})
