import { expect, test } from '@playwright/test'

for (const width of [1440, 390]) {
  test(`all examples and sample welcome guidance at ${width}px`, async ({ page }) => {
    test.setTimeout(120000)
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/', { waitUntil: 'domcontentloaded' })
    await page.getByRole('link', { name: 'View all examples' }).click()
    await expect(page).toHaveURL('/examples')
    await expect(page.locator('article')).toHaveCount(321, { timeout: 20000 })
    await page.getByRole('textbox', { name: 'Search examples' }).fill('Button Control')
    await expect(page.locator('article')).toHaveCount(1)
    await page.getByRole('button', { name: 'Open starter' }).click()
    await expect(page).toHaveURL(/\/project\//)
    if (width < 900) await page.getByRole('button', { name: 'Agent', exact: true }).click()
    const message = page.getByRole('article', { name: 'WireUp message' })
    await expect(message).toContainText('Welcome to Button Control', { timeout: 15000 })
    await expect(message).toContainText('What is connected', { timeout: 15000 })
    await expect(message).toContainText('Compile', { timeout: 15000 })
    await expect(message).toContainText('Disconnect power', { timeout: 15000 })
    await page.reload()
    if (width < 900) await page.getByRole('button', { name: 'Agent', exact: true }).click()
    await expect(message).toContainText('Welcome to Button Control', { timeout: 15000 })
    await page.screenshot({ path: `test-results/sample-guide-${width}.png` })
    await page.goto('/examples', { waitUntil: 'domcontentloaded' })
    await page.getByRole('combobox', { name: 'Filter example category' }).selectOption('displays')
    await page.getByRole('combobox', { name: 'Filter example board' }).selectOption('arduino-uno')
    await page.getByRole('textbox', { name: 'Search examples' }).fill('uno-oled-4pin-i2c')
    await expect(page.locator('article')).toHaveCount(1)
    await expect(page.locator('article')).toContainText('Simulation-ready hardware · compile/run unverified')
    await page.getByText('Requirements / simulation scope', { exact: true }).click()
    await expect(page.locator('article')).toContainText('Adafruit SSD1306')
    await page.getByRole('button', { name: 'Open example', exact: true }).click()
    await expect(page).toHaveURL(/\/project\//)
    const projectId = page.url().split('/project/')[1]
    const projectResponse = await page.request.get(`/api/hardware/projects/${projectId}`)
    expect(projectResponse.ok()).toBeTruthy()
    const project = await projectResponse.json()
    expect(project.board).toBe('arduino-uno')
    expect(project.firmware.source).toContain('#include <Adafruit_SSD1306.h>')
    expect(project.components.some((part: { type: string }) => part.type === 'ssd1306-i2c-4pin')).toBeTruthy()
    await page.goto('/examples', { waitUntil: 'domcontentloaded' })
    await page.getByRole('combobox', { name: 'Filter simulation scope' }).selectOption('partial')
    await page.getByRole('textbox', { name: 'Search examples' }).fill('pico-oled-4pin-i2c')
    await expect(page.locator('article')).toHaveCount(1)
    await expect(page.locator('article')).toContainText('Partial simulation support')
    await expect(page.getByRole('button', { name: 'Open example', exact: true })).toBeEnabled()
    await page.getByRole('combobox', { name: 'Filter simulation scope' }).selectOption('blocked')
    await page.getByRole('textbox', { name: 'Search examples' }).fill('ky-040-rotary-encoder')
    await expect(page.locator('article')).toHaveCount(1)
    await expect(page.locator('article')).toContainText('cannot open safely')
    await expect(page.getByRole('button', { name: 'Open example', exact: true })).toHaveCount(0)
    await page.getByRole('combobox', { name: 'Filter simulation scope' }).selectOption('all')
    await page.getByRole('textbox', { name: 'Search examples' }).fill('no-such-prototype-xyz')
    await expect(page.getByText('No examples match these filters.')).toBeVisible()
  })
}
