import { expect, test } from '@playwright/test'
for(const width of [1440,390]) {
 test(`automatic heading and upward model selector at ${width}px`,async({page,request})=>{
  await page.setViewportSize({width,height:800})
  await page.route('**/api/health',route=>route.fulfill({json:{configured:true,model:'gpt-6.1-sol',providers:[{id:'azure',label:'Azure',model:'gpt-6.1-sol',configured:true},{id:'groq',label:'Groq',model:'gpt-oss-120b',configured:true},{id:'nvidia',label:'NVIDIA',model:'glm-5.3',configured:true}]}}))
  await page.route('**/api/chat',route=>route.fulfill({contentType:'application/x-ndjson',body:JSON.stringify({type:'text',channel:'answer',text:'Project request received.'})+'\n'+JSON.stringify({type:'done'})+'\n'}))
  await page.goto('/')
  const input=page.getByRole('textbox',{name:'Describe your hardware prototype'})
  await input.fill('build a mini calculator using arduino uno')
  await page.getByRole('button',{name:'Build prototype',exact:true}).click()
  await expect(page.locator('.hw-project-title')).toHaveText('Arduino Uno Mini Calculator')
  if(width<900)await page.getByRole('button',{name:'Agent',exact:true}).click()
  const trigger=page.locator('[data-slot=model-selector-trigger]')
  await trigger.click()
  const menu=page.locator('[data-slot=model-selector-content]')
  await expect(menu).toBeVisible()
  await page.waitForTimeout(350)
  const box=await menu.boundingBox();const anchor=await trigger.boundingBox()
  expect(box!.y).toBeGreaterThanOrEqual(0)
  expect(box!.y+box!.height).toBeLessThanOrEqual(anchor!.y)
  expect(box!.x+box!.width).toBeLessThanOrEqual(width)
  await page.getByRole('option',{name:'gpt-oss-120b',exact:false}).click()
  await expect(menu).toHaveCount(0)
  await expect(trigger).toContainText('gpt-oss-120b')
  const id=page.url().split('/').pop()
  const project=await(await request.get(`/api/hardware/projects/${id}`)).json()
  expect(project.name).toBe('Arduino Uno Mini Calculator')
 })
}
