import {expect,test} from '@playwright/test'
test('live provider MCQs to actual LED build',async({page,request})=>{
 test.skip(process.env.WIREUP_LIVE_AUDIT !== '1', 'Live provider checks are opt-in and incur usage.')
 test.setTimeout(300000)
 if(process.env.WIREUP_LIVE_PROVIDER)await page.addInitScript(provider=>localStorage.setItem('wireup.model-provider',provider),process.env.WIREUP_LIVE_PROVIDER)
 const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message))
 await expect.poll(async()=>{try{return (await request.get('/api/health')).status()}catch{return 0}},{timeout:90000}).toBe(200)
 const project=await(await request.post('/api/hardware/projects',{data:{name:'Live agent audit',board:'arduino-uno'}})).json()
 await page.goto(`/project/${project.id}`)
 const input=page.getByRole('textbox',{name:'Message WireUp'})
 await input.fill('Build a simple Arduino Uno LED blink circuit with an external LED and a 220 ohm resistor. Blink one second on and one second off. Generate firmware and compile it. No simulation is needed.')
 await page.getByRole('button',{name:'Send message',exact:true}).click()
 const form=page.getByRole('form',{name:'Project requirements'})
 await expect(form).toBeVisible({timeout:90000})
 console.log('QUESTIONS',await form.locator('legend').allTextContents())
 expect(await form.locator('fieldset').count()).toBe(10)
 for(const fieldset of await form.locator('fieldset').all())await fieldset.getByRole('radio',{name:'Let AI choose',exact:false}).check()
 await form.getByRole('button',{name:'Confirm and build circuit'}).click()
 await expect(page.getByRole('dialog',{name:'Set up your project'})).toHaveCount(0)
 await expect(page.getByRole('button',{name:'Send message',exact:true})).toBeVisible({timeout:180000})
 const result=await(await request.get(`/api/hardware/projects/${project.id}`)).json()
 console.log('LIVE RESULT',JSON.stringify({board:result.board,components:result.components,wires:result.wires,firmware:result.firmware,compiler:result.compiler}))
 console.log('CHAT',await page.getByRole('log',{name:'Conversation'}).innerText())
 await expect(page.getByRole('form',{name:'Prototype feasibility review'})).toHaveCount(0)
 expect(result.components.some((part:{type:string})=>part.type==='led')).toBe(true)
 expect(result.wires.length).toBeGreaterThanOrEqual(3)
 expect(result.firmware.source).toContain('void setup')
 expect(result.compiler?.success ?? result.compiler?.status==='simulation_ready').toBeTruthy()
 expect(errors).toEqual([])
})
