import {expect,test} from '@playwright/test'
for(const board of ['pi-pico','pi-pico-w'])test(`${board} existing potentiometer model reads real ADC`,async({page,request})=>{
 test.setTimeout(420000)
 const project=await(await request.post('/api/hardware/projects',{data:{name:`${board} analog`,board}})).json()
 const command=async(name:string,args:Record<string,unknown>)=>{const r=await request.post(`/api/hardware/project/${project.id}/command`,{data:{name,args}});expect(r.ok(),await r.text()).toBe(true);return r.json()}
 await command('add_component',{type:'potentiometer',id:'pot',properties:{value:512},x:420,y:150})
 for(const [pin,to] of [['3V3','VCC'],['GND','GND'],['GP26','SIG']])await command('connect_wire',{from:{component:'board',pin},to:{component:'pot',pin:to}})
 await command('generate_firmware',{source:'void setup(){Serial1.begin(9600);}\nvoid loop(){Serial1.println(analogRead(A0));delay(100);}'})
 await page.goto(`/project/${project.id}`)
 await expect(page.getByText('Runtime: Connected')).toBeVisible({timeout:30000})
 await page.getByRole('button',{name:'Compile',exact:true}).click()
 await expect(page.getByRole('button',{name:'Run',exact:true})).toBeEnabled({timeout:330000})
 await page.getByRole('button',{name:'Run',exact:true}).click()
 await expect(page.getByRole('button',{name:'Stop',exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Serial monitor',exact:true}).click()
 await expect(page.getByLabel('Serial output',{exact:true})).toContainText(/\b51[0-9]\b/,{timeout:20000})
 await page.locator('wokwi-potentiometer').evaluate(element=>{(element as HTMLElement &{value:number}).value=768;element.dispatchEvent(new Event('input'))})
 await expect(page.getByLabel('Serial output',{exact:true})).toContainText(/\b76[0-9]\b/,{timeout:15000})
 await page.getByRole('button',{name:'Stop',exact:true}).click()
})
