import {expect,test} from '@playwright/test'
for(const board of ['arduino-uno','arduino-nano'])test(`${board} KY040 events reach actual interrupt firmware`,async({page,request})=>{
 test.setTimeout(150000)
 const project=await(await request.post('/api/hardware/projects',{data:{name:'Encoder',board}})).json()
 const command=async(name:string,args:Record<string,unknown>)=>{const r=await request.post(`/api/hardware/project/${project.id}/command`,{data:{name,args}});expect(r.ok(),await r.text()).toBe(true)}
 await command('add_component',{type:'ky-040',id:'encoder',x:450,y:150})
 for(const [pin,target] of [['5V','VCC'],['GND','GND'],['2','CLK'],['3','DT'],['4','SW']])await command('connect_wire',{from:{component:'board',pin},to:{component:'encoder',pin:target}})
 await command('generate_firmware',{source:'volatile int count=0;void tick(){count+=digitalRead(3)==LOW?1:-1;}void setup(){Serial.begin(9600);pinMode(2,INPUT_PULLUP);pinMode(3,INPUT_PULLUP);pinMode(4,INPUT_PULLUP);attachInterrupt(digitalPinToInterrupt(2),tick,RISING);}\nvoid loop(){Serial.print(count);Serial.print(",");Serial.println(digitalRead(4));delay(50);}'})
 await command('compile_firmware',{})
 await page.goto(`/project/${project.id}`)
 await page.getByRole('button',{name:'Run',exact:true}).click()
 await page.getByRole('button',{name:'Serial monitor',exact:true}).click()
 const element=page.locator('wokwi-ky-040');const output=page.getByLabel('Serial output',{exact:true})
 await expect(output).toContainText('0,1',{timeout:10000})
 await element.evaluate(e=>e.dispatchEvent(new Event('rotate-cw')))
 await expect(output).toContainText('1,1',{timeout:10000})
 await element.evaluate(e=>e.dispatchEvent(new Event('rotate-ccw')))
 await element.evaluate(e=>e.dispatchEvent(new Event('button-press')))
 await expect(output).toContainText('0,0',{timeout:10000})
 await element.evaluate(e=>e.dispatchEvent(new Event('button-release')))
 await page.getByRole('button',{name:'Stop',exact:true}).click()
 await element.evaluate(e=>e.dispatchEvent(new Event('rotate-cw')))
 await page.getByRole('button',{name:'Run',exact:true}).click()
 await expect(output).toContainText('0,1',{timeout:10000})
 await page.getByRole('button',{name:'Stop',exact:true}).click()
})
