import {expect,test} from '@playwright/test'
for(const board of ['arduino-uno','arduino-nano','arduino-mega'])test(`${board} slide switch changes real rail-selected GPIO`,async({page,request})=>{
 test.setTimeout(150000)
 const project=await(await request.post('/api/hardware/projects',{data:{name:'Slide switch',board}})).json()
 const command=async(name:string,args:Record<string,unknown>)=>{const r=await request.post(`/api/hardware/project/${project.id}/command`,{data:{name,args}});expect(r.ok(),await r.text()).toBe(true)}
 await command('add_component',{type:'slide-switch',id:'switch',x:440,y:160})
 await command('connect_wire',{from:{component:'board',pin:'GND'},to:{component:'switch',pin:'1'}})
 await command('connect_wire',{from:{component:'board',pin:'7'},to:{component:'switch',pin:'2'}})
 await command('connect_wire',{from:{component:'board',pin:'5V'},to:{component:'switch',pin:'3'}})
 await command('generate_firmware',{source:'void setup(){Serial.begin(9600);pinMode(7,INPUT_PULLUP);}\nvoid loop(){Serial.println(digitalRead(7));delay(50);}'})
 await command('compile_firmware',{})
 await page.goto(`/project/${project.id}`)
 await expect(page.getByText('Runtime: Connected',{exact:true})).toBeVisible({timeout:30000})
 await page.getByRole('button',{name:'Run',exact:true}).click()
 await page.getByRole('button',{name:'Serial monitor',exact:true}).click()
 const output=page.getByLabel('Serial output',{exact:true})
 await expect(output).toContainText('0',{timeout:10000})
 await page.locator('wokwi-slide-switch').evaluate(element=>{(element as HTMLElement &{value:number}).value=1;element.dispatchEvent(new Event('change'))})
 await expect(output).toContainText('1',{timeout:10000})
 await page.getByRole('button',{name:'Stop',exact:true}).click()
 await page.getByRole('button',{name:'Run',exact:true}).click()
 await expect(page.getByRole('button',{name:'Stop',exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Stop',exact:true}).click()
})
