import {expect,test} from '@playwright/test'
for(const width of [1440,390])test(`drag previews move cables before one committed update at ${width}px`,async({page,request})=>{
 const project=await(await request.post('/api/hardware/projects',{data:{name:'Smooth cable',board:'arduino-uno'}})).json()
 await request.post(`/api/hardware/project/${project.id}/command`,{data:{name:'add_component',args:{type:'led',id:'led',x:380,y:180}}})
 await request.post(`/api/hardware/project/${project.id}/command`,{data:{name:'connect_wire',args:{from:{component:'board',pin:'13'},to:{component:'led',pin:'A'}}}})
 await page.setViewportSize({width,height:900});await page.goto(`/project/${project.id}`)
 const handle=page.getByRole('button',{name:'Select led',exact:true})
 await handle.scrollIntoViewIfNeeded()
 const path=page.locator('.hw-wires g path').first();await expect(path).toHaveAttribute('d',/Q/)
 const before=await path.getAttribute('d');const box=await handle.boundingBox()
 await page.mouse.move(box!.x+box!.width/2,box!.y+box!.height/2);await page.mouse.down();await page.mouse.move(box!.x+box!.width/2+50,box!.y+box!.height/2+40,{steps:12})
 await expect(path).not.toHaveAttribute('d',before!)
 const during=await(await request.get(`/api/hardware/projects/${project.id}`)).json()
 expect(during.components.find((p:{id:string})=>p.id==='led').x).toBe(380)
 await page.mouse.up()
 await expect.poll(async()=>{const state=await(await request.get(`/api/hardware/projects/${project.id}`)).json();return state.components.find((p:{id:string})=>p.id==='led').x}).toBeGreaterThan(400)
 await expect(page.getByRole('toolbar',{name:'Actions for led'})).toBeVisible()
 await page.getByRole('button',{name:'Rotate led',exact:true}).click()
 await expect.poll(async()=>{const state=await(await request.get(`/api/hardware/projects/${project.id}`)).json();return state.components.find((p:{id:string})=>p.id==='led').rotation}).toBe(90)
})

test('simulated network settings validate and remain scoped to current project',async({page,request})=>{
 const project=await(await request.post('/api/hardware/projects',{data:{name:'WiFi config',board:'esp32-c3'}})).json()
 await page.goto(`/project/${project.id}`)
 await page.getByRole('button',{name:'Select board',exact:true}).click()
 await page.getByRole('button',{name:'Simulated Wi-Fi settings',exact:true}).click()
 const dialog=page.getByRole('dialog',{name:'Simulated Wi-Fi network'})
 await dialog.getByLabel('Simulated network SSID').fill('WireUpTest')
 await dialog.getByLabel('Simulated network password').fill('short')
 await dialog.getByRole('button',{name:'Apply network settings'}).click()
 await expect(dialog.getByRole('alert')).toContainText('8–63')
 await dialog.getByLabel('Simulated network password').fill('wireuptest123')
 await dialog.getByRole('button',{name:'Apply network settings'}).click()
 await expect(dialog).toContainText('apply when simulation next starts')
 await expect(dialog).toContainText('Internet access and external networking are not connected')
 await dialog.getByRole('button',{name:'Close simulated Wi-Fi'}).click()
 await page.getByRole('button',{name:'Simulated Wi-Fi settings',exact:true}).click()
 await expect(dialog.getByLabel('Simulated network SSID')).toHaveValue('WireUpTest')
})
