import {expect,test} from '@playwright/test'
for(const width of [1440,390])test(`wire details show actual pins at ${width}px`,async({page,request})=>{
 const project=await(await request.post('/api/hardware/projects',{data:{name:'Wire details',board:'arduino-uno'}})).json()
 await request.post(`/api/hardware/project/${project.id}/command`,{data:{name:'add_component',args:{type:'led',id:'led',x:400,y:200}}})
 await request.post(`/api/hardware/project/${project.id}/command`,{data:{name:'connect_wire',args:{from:{component:'board',pin:'13'},to:{component:'led',pin:'A'}}}})
 await page.setViewportSize({width,height:900});await page.goto(`/project/${project.id}`)
 const wire=page.getByRole('button',{name:'Inspect wire board.13 to led.A',exact:true})
 await expect(wire).toBeVisible({timeout:30000});await wire.focus();await wire.press('Enter')
 const card=page.getByRole('dialog',{name:'Wire connection details'})
 await expect(card).toContainText('board');await expect(card).toContainText('Pin 13');await expect(card).toContainText('led');await expect(card).toContainText('Pin A')
 await expect(page.locator('.hw-wires text')).toContainText(['board · 13','led · A'])
 await card.getByRole('button',{name:'Show board pin 13'}).click()
 await expect(page.getByRole('toolbar',{name:'Actions for board'})).toBeVisible()
 await card.getByRole('button',{name:'Close wire details'}).click();await expect(card).toHaveCount(0)
 await page.locator('.hw-canvas-viewport').evaluate(element=>{element.scrollLeft=240})
 const point=await wire.evaluate(element=>{const path=element as SVGPathElement;for(let length=10;length<path.getTotalLength();length+=10){const p=path.getPointAtLength(length);const screen=new DOMPoint(p.x,p.y).matrixTransform(path.getScreenCTM()!);if(document.elementFromPoint(screen.x,screen.y)===element)return {x:screen.x,y:screen.y}}throw new Error('No visible wire stroke available for clicking')})
 await page.mouse.click(point.x,point.y);await expect(card).toBeVisible();await card.getByRole('button',{name:'Close wire details'}).click()
 await page.reload();await wire.focus();await wire.press('Enter');await expect(card).toContainText('Pin 13')
})
